export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const INITIAL_INGREDIENTS_FAIL = 'INITIAL_INGREDIENTS_FAIL';